#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
%define keepstatic 1
Name     : libiec61883
Version  : 1.2.0
Release  : 5
URL      : https://mirrors.edge.kernel.org/pub/linux/libs/ieee1394/libiec61883-1.2.0.tar.xz
Source0  : https://mirrors.edge.kernel.org/pub/linux/libs/ieee1394/libiec61883-1.2.0.tar.xz
Summary  : Streaming library for IEEE1394
Group    : Development/Tools
License  : GPL-2.0
Requires: libiec61883-bin = %{version}-%{release}
Requires: libiec61883-lib = %{version}-%{release}
Requires: libiec61883-man = %{version}-%{release}
BuildRequires : pkgconfig(libraw1394)

%description
http://www.linux1394.org/
Overview
--------
This library is an implementation of IEC 61883, part 1 (CIP, plug registers,
and CMP), part 2 (DV-SD), part 4 (MPEG2-TS), and part 6 (AMDTP). Outside of
IIDC, nearly all FireWire multimedia devices use IEC 61883 protocols.

%package bin
Summary: bin components for the libiec61883 package.
Group: Binaries

%description bin
bin components for the libiec61883 package.


%package dev
Summary: dev components for the libiec61883 package.
Group: Development
Requires: libiec61883-lib = %{version}-%{release}
Requires: libiec61883-bin = %{version}-%{release}
Provides: libiec61883-devel = %{version}-%{release}
Requires: libiec61883 = %{version}-%{release}

%description dev
dev components for the libiec61883 package.


%package lib
Summary: lib components for the libiec61883 package.
Group: Libraries

%description lib
lib components for the libiec61883 package.


%package man
Summary: man components for the libiec61883 package.
Group: Default

%description man
man components for the libiec61883 package.


%package staticdev
Summary: staticdev components for the libiec61883 package.
Group: Default
Requires: libiec61883-dev = %{version}-%{release}

%description staticdev
staticdev components for the libiec61883 package.


%prep
%setup -q -n libiec61883-1.2.0
cd %{_builddir}/libiec61883-1.2.0

%build
## build_prepend content
find . -type f -name 'configure' -exec sed -i 's/\-fPIC/\-fpic/g' {} \;
find . -type f -name 'configure.ac' -exec sed -i 's/\-fPIC/\-fpic/g' {} \;
find . -type f -name 'libtool' -exec sed -i 's/\-fPIC/\-fpic/g' {} \;
find . -type f -name 'libtool.m4' -exec sed -i 's/\-fPIC/\-fpic/g' {} \;
find . -type f -name '*.m4' -exec sed -i 's/\-fPIC/\-fpic/g' {} \;
echo "AM_MAINTAINER_MODE([disable])" >> configure.ac
autoreconf -fiv
## build_prepend end
unset http_proxy
unset https_proxy
unset no_proxy
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1587268417
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="-O3 -Wall -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-sort-common -Wl,-z,now -Wl,-z,relro -Wno-error -Wp,-D_REENTRANT -falign-functions=32 -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -feliminate-unused-debug-types -ffat-lto-objects -fipa-pta -floop-nest-optimize -flto=12 -fno-PIC -fno-PIE -fno-math-errno -fno-pie -fno-plt -fno-semantic-interposition -fno-stack-protector -fno-trapping-math -fpic -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-vectorize -funroll-loops -fuse-ld=bfd -fuse-linker-plugin -g -m64 -malign-data=cacheline -march=native -mtls-dialect=gnu2 -mtune=native -pipe "
export FCFLAGS="-O3 -Wall -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-sort-common -Wl,-z,now -Wl,-z,relro -Wno-error -Wp,-D_REENTRANT -falign-functions=32 -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -feliminate-unused-debug-types -ffat-lto-objects -fipa-pta -floop-nest-optimize -flto=12 -fno-PIC -fno-PIE -fno-math-errno -fno-pie -fno-plt -fno-semantic-interposition -fno-stack-protector -fno-trapping-math -fpic -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-vectorize -funroll-loops -fuse-ld=bfd -fuse-linker-plugin -g -m64 -malign-data=cacheline -march=native -mtls-dialect=gnu2 -mtune=native -pipe "
export FFLAGS="-O3 -Wall -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-sort-common -Wl,-z,now -Wl,-z,relro -Wno-error -Wp,-D_REENTRANT -falign-functions=32 -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -feliminate-unused-debug-types -ffat-lto-objects -fipa-pta -floop-nest-optimize -flto=12 -fno-PIC -fno-PIE -fno-math-errno -fno-pie -fno-plt -fno-semantic-interposition -fno-stack-protector -fno-trapping-math -fpic -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-vectorize -funroll-loops -fuse-ld=bfd -fuse-linker-plugin -g -m64 -malign-data=cacheline -march=native -mtls-dialect=gnu2 -mtune=native -pipe "
export CFFLAGS="-O3 -Wall -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-sort-common -Wl,-z,now -Wl,-z,relro -Wno-error -Wp,-D_REENTRANT -falign-functions=32 -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -feliminate-unused-debug-types -ffat-lto-objects -fipa-pta -floop-nest-optimize -flto=12 -fno-PIC -fno-PIE -fno-math-errno -fno-pie -fno-plt -fno-semantic-interposition -fno-stack-protector -fno-trapping-math -fpic -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-vectorize -funroll-loops -fuse-ld=bfd -fuse-linker-plugin -g -m64 -malign-data=cacheline -march=native -mtls-dialect=gnu2 -mtune=native -pipe "
export LDFLAGS="-O3 -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--hash-style=gnu -Wl,-O2 -Wl,-sort-common -Wl,-z,now -Wl,-z,relro -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -ffat-lto-objects -fipa-pta -floop-nest-optimize -flto=12 -fno-PIC -fno-PIE -fno-pie -fno-plt -fno-semantic-interposition -fno-stack-protector -fpic -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-vectorize -funroll-loops -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -march=native -mtls-dialect=gnu2 -mtune=native "
export CXXFLAGS="-O3 -Wall -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-sort-common -Wl,-z,now -Wl,-z,relro -Wno-error -Wp,-D_REENTRANT -falign-functions=32 -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -feliminate-unused-debug-types -ffat-lto-objects -fipa-pta -floop-nest-optimize -flto=12 -fno-PIC -fno-PIE -fno-math-errno -fno-pie -fno-plt -fno-semantic-interposition -fno-stack-protector -fno-trapping-math -fpic -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-vectorize -funroll-loops -fuse-ld=bfd -fuse-linker-plugin -fvisibility-inlines-hidden -g -m64 -malign-data=cacheline -march=native -mtls-dialect=gnu2 -mtune=native -pipe "
%configure  --enable-static --enable-shared --disable-maintainer-mode
## make_prepend content
find . -type f -name 'Makefile' -exec sed -i 's/\-fPIC/\-fpic/g' {} \;
find . -type f -name 'configure' -exec sed -i 's/\-fPIC/\-fpic/g' {} \;
find . -type f -name 'configure.ac' -exec sed -i 's/\-fPIC/\-fpic/g' {} \;
find . -type f -name 'libtool' -exec sed -i 's/\-fPIC/\-fpic/g' {} \;
find . -type f -name 'libtool.m4' -exec sed -i 's/\-fPIC/\-fpic/g' {} \;
find . -type f -name '*.m4' -exec sed -i 's/\-fPIC/\-fpic/g' {} \;
find . -type f -name 'config.status' -exec sed -i 's/\-fPIC/\-fpic/g' {} \;
## make_prepend end
make  %{?_smp_mflags}

%check
export LANG=C.UTF-8
unset http_proxy
unset https_proxy
unset no_proxy
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1587268417
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/plugctl
/usr/bin/plugreport

%files dev
%defattr(-,root,root,-)
/usr/include/libiec61883/iec61883.h
/usr/lib64/pkgconfig/libiec61883.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/libiec61883.so
/usr/lib64/libiec61883.so.0
/usr/lib64/libiec61883.so.0.1.1

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/plugctl.1
/usr/share/man/man1/plugreport.1

%files staticdev
%defattr(-,root,root,-)
/usr/lib64/libiec61883.a
